name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Docker Image
        run: docker build -t flask-docker-app .

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{"AKIAYPXRVENY7J3VNYXI" }}
          username: ${{ ec2-user }}
          key: ${{ "29Y+wyfiNRO3ji+7Rp/BNwCksy8D9JrAG6M5o//1" }}
          source: ./
          target: /path/to/your/app

      - name: SSH into EC2 and restart Docker container
        run: |
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd /path/to/your/app && docker-compose down && docker-compose up -d"